# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('released_year', models.CharField(blank=True, max_length=4, null=True)),
                ('rating', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genres',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres_movie', to='movies.Movie'),
        ),
    ]
